speller:
  algebra:
    自然码: # 全拼转自然码(包含拆字)
      - derive/^([jqxy])u(?=^|$|')/$1v/
      - derive/'([jqxy])u(?=^|$|')/'$1v/
      - derive/^([aoe])([ioun])(?=^|$|')/$1$1$2/
      - derive/'([aoe])([ioun])(?=^|$|')/'$1$1$2/
      - xform/^([aoe])(ng)?(?=^|$|')/$1$1$2/
      - xform/'([aoe])(ng)?(?=^|$|')/'$1$1$2/
      - xform/iu(?=^|$|')/<q>/
      - xform/[iu]a(?=^|$|')/<w>/
      - xform/[uv]an(?=^|$|')/<r>/
      - xform/[uv]e(?=^|$|')/<t>/
      - xform/ing(?=^|$|')|uai(?=^|$|')/<y>/
      - xform/^sh/<u>/
      - xform/^ch/<i>/
      - xform/^zh/<v>/
      - xform/'sh/'<u>/
      - xform/'ch/'<i>/
      - xform/'zh/'<v>/
      - xform/uo(?=^|$|')/<o>/
      - xform/[uv]n(?=^|$|')/<p>/
      - xform/([a-z>])i?ong(?=^|$|')/$1<s>/
      - xform/[iu]ang(?=^|$|')/<d>/
      - xform/([a-z>])en(?=^|$|')/$1<f>/
      - xform/([a-z>])eng(?=^|$|')/$1<g>/
      - xform/([a-z>])ang(?=^|$|')/$1<h>/
      - xform/ian(?=^|$|')/<m>/
      - xform/([a-z>])an(?=^|$|')/$1<j>/
      - xform/iao(?=^|$|')/<c>/
      - xform/([a-z>])ao(?=^|$|')/$1<k>/
      - xform/([a-z>])ai(?=^|$|')/$1<l>/
      - xform/([a-z>])ei(?=^|$|')/$1<z>/
      - xform/ie(?=^|$|')/<x>/
      - xform/ui(?=^|$|')/<v>/
      - xform/([a-z>])ou(?=^|$|')/$1<b>/
      - xform/in(?=^|$|')/<n>/
      - xform/<|>//
    九宫格:
      # fn* tuw gsa
      # jyk pix hde
      # mzc rlq bvo
      - xform/f/<11>/
      - xform/n/<12>/
      - xform/t/<21>/
      - xform/u/<22>/
      - xform/w/<23>/
      - xform/g/<31>/
      - xform/s/<32>/
      - xform/a/<33>/
      - xform/j/<41>/
      - xform/y/<42>/
      - xform/k/<43>/
      - xform/p/<51>/
      - xform/i/<52>/
      - xform/x/<53>/
      - xform/h/<61>/
      - xform/d/<62>/
      - xform/e/<63>/
      - xform/m/<71>/
      - xform/z/<72>/
      - xform/c/<73>/
      - xform/r/<81>/
      - xform/l/<82>/
      - xform/q/<83>/
      - xform/b/<91>/
      - xform/v/<92>/
      - xform/o/<93>/

      - xform/<[1-9]1><[1-9]1>/${0}1/
      - xform/<[1-9]1><[1-9]2>/${0}2/
      - xform/<[1-9]1><[1-9]3>/${0}3/
      - xform/<[1-9]2><[1-9]1>/${0}4/
      - xform/<[1-9]2><[1-9]2>/${0}5/
      - xform/<[1-9]2><[1-9]3>/${0}6/
      - xform/<[1-9]3><[1-9]1>/${0}7/
      - xform/<[1-9]3><[1-9]2>/${0}8/
      - xform/<[1-9]3><[1-9]3>/${0}9/
      - xform/<([1-9])[1-3]>/${1}/
    imr_double:
      __include: speller/algebra/自然码
    imr_t93:
      __include: speller/algebra/自然码
      __append:
        __include: speller/algebra/九宫格
        __append:
          - derive/^([1-9][1-9])[1-9]$/${1}0/
    radical_double:
      __include: speller/algebra/自然码
      __append: # 去掉分隔符
        - xform/'//
    radical_t93:
      __include: speller/algebra/自然码
      __append:
        __include: speller/algebra/九宫格
        __append:
          - xform/'//
translator:
  preedit_format:
    imr_t93:
      # 第三键
      - xform/(^|[ '])([1-9])([1-9])1/${1}<${2}1><${3}1>/
      - xform/(^|[ '])([1-9])([1-9])2/${1}<${2}1><${3}2>/
      - xform/(^|[ '])([1-9])([1-9])3/${1}<${2}1><${3}3>/
      - xform/(^|[ '])([1-9])([1-9])4/${1}<${2}2><${3}1>/
      - xform/(^|[ '])([1-9])([1-9])5/${1}<${2}2><${3}2>/
      - xform/(^|[ '])([1-9])([1-9])6/${1}<${2}2><${3}3>/
      - xform/(^|[ '])([1-9])([1-9])7/${1}<${2}3><${3}1>/
      - xform/(^|[ '])([1-9])([1-9])8/${1}<${2}3><${3}2>/
      - xform/(^|[ '])([1-9])([1-9])9/${1}<${2}3><${3}3>/
      # 九宫格数字映射
      # mj* buh gqo 
      # kyn aiw xde
      # fzr tlp cvs
      - xform/<11>/f/
      - xform/<12>/n/
      - xform/<21>/t/
      - xform/<22>/u/
      - xform/<23>/w/
      - xform/<31>/g/
      - xform/<32>/s/
      - xform/<33>/a/
      - xform/<41>/j/
      - xform/<42>/y/
      - xform/<43>/k/
      - xform/<51>/p/
      - xform/<52>/i/
      - xform/<53>/x/
      - xform/<61>/h/
      - xform/<62>/d/
      - xform/<63>/e/
      - xform/<71>/m/
      - xform/<72>/z/
      - xform/<73>/c/
      - xform/<81>/r/
      - xform/<82>/l/
      - xform/<83>/q/
      - xform/<91>/b/
      - xform/<92>/v/
      - xform/<93>/o/

      # 自然码双拼
      - xform/(^|[ '])aa/${1}a/
      - xform/(^|[ '])ee/${1}e/
      - xform/(^|[ '])oo/${1}o/
      - xform/([bpmnljqxy])n/${1}in/
      - xform/(\w)g/${1}eng/
      - xform/(\w)q/${1}iu/
      - xform/([gkhvuirzcs])w/${1}ua/
      - xform/(\w)w/${1}ia/
      - xform/([dtnlgkhjqxyvuirzcs])r/${1}uan/
      - xform/(\w)t/${1}ve/
      - xform/([gkhvuirzcs])y/${1}uai/
      - xform/(\w)y/${1}ing/
      - xform/([dtnlgkhvuirzcs])o/${1}uo/
      - xform/(\w)p/${1}un/
      - xform/([jqx])s/${1}iong/
      - xform/(\w)s/${1}ong/
      - xform/([jqxnlb])d/${1}iang/
      - xform/(\w)d/${1}uang/
      - xform/(\w)f/${1}en/
      - xform/(\w)h/${1}ang/
      - xform/(\w)j/${1}an/
      - xform/(\w)k/${1}ao/
      - xform/(\w)l/${1}ai/
      - xform/(\w)z/${1}ei/
      - xform/(\w)x/${1}ie/
      - xform/(\w)c/${1}iao/
      - xform/([dtgkhvuirzcs])v/${1}ui/
      - xform/(\w)b/${1}ou/
      - xform/(\w)m/${1}ian/
      - xform/([aoe])\1(\w)/${1}${2}/
      - xform/(^|[ '])v/${1}zh/
      - xform/(^|[ '])i/${1}ch/
      - xform/(^|[ '])u/${1}sh/
      - xform/([jqxy])v/${1}u/
      - xform/([nl])v/${1}ü/
      - xform/ü/v/  # ü 显示为 v
      - xform/(?<=[A-Z])\s(?=[A-Z])//  # 消除大写字母之间的空格
pin_cand_filter:
  imr_double: 
    # de
    - d	的
    - de	的 地 得
    # ta
    - ta	他 她 它
  imr_t93:
    # de
    - 6	的
    - 66	的
    - 666	的 地 得
    # ta
    - 851	他 她 它